import React from "react";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import Head from "next/head";
import getLPTheme from "@/data/getLPTheme";
import Hero from "@/components/Hero/Hero";
import About from "@/components/About/About";
import Projects from "@/components/Projects/Projects";
import Certificates from "@/components/Certificates/Certificates";
import MainLayout from "@/components/Layout/MainLayout";
import NewsLayout from "@/components/Layout/NewsLayout";
import Aos from "aos";
import News from "@/components/News/News";
import SlideNews from "@/components/SlideNews/SlideNews";
import RecentNews from "@/components/RecentNews/RecentNews";
// import Slidetest from "@/components/Slidetest";
import NewsCategoryList from "@/components/NewsCategoryList/NewsCategoryList";
import FaceNews from "@/components/FaceNews/FaceNews";
export default function Home() {
  const LPtheme = createTheme(getLPTheme("light"));
  React.useEffect(() => {
    Aos.init({ duration: 800, once: true });
  }, []);

  return (
    <ThemeProvider theme={LPtheme}>
      <Head>
        <title>App demo news</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewsLayout>
        <News />
        <SlideNews />
        {/* <NewsCategoryList /> */}
        <FaceNews />
        <RecentNews />
        {/* <Slidetest /> */}
      </NewsLayout>
    </ThemeProvider>
  );
}
